/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolproject;


public class adminMainMenu extends javax.swing.JFrame {
    private String username;
    private EditProfileScreen eprofile = new EditProfileScreen();
    //private LoadScreen lscreen = new LoadScreen();
    
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        signOutBT = new javax.swing.JButton();
        adminIcon = new javax.swing.JLabel();
        adminTxt = new javax.swing.JTextField();
        adminUserTF = new javax.swing.JTextField();
        editProfileBT = new javax.swing.JButton();
        addStudentBT = new javax.swing.JButton();
        createAccountBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 1000));

        backgroundPanel.setBackground(new java.awt.Color(250, 228, 188));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(1000, 1000));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signOutBT.setBackground(new java.awt.Color(65, 147, 211));
        signOutBT.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        signOutBT.setForeground(new java.awt.Color(255, 255, 255));
        signOutBT.setText("Sign Out");
        signOutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBTActionPerformed(evt);
            }
        });
        backgroundPanel.add(signOutBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        adminIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/adminUser.png"))); // NOI18N
        backgroundPanel.add(adminIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 200, 200));

        adminTxt.setEditable(false);
        adminTxt.setBackground(new java.awt.Color(250, 228, 188));
        adminTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        adminTxt.setText("Admin User:");
        adminTxt.setBorder(null);
        adminTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminTxtActionPerformed(evt);
            }
        });
        backgroundPanel.add(adminTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        adminUserTF.setEditable(false);
        adminUserTF.setBackground(new java.awt.Color(250, 228, 188));
        adminUserTF.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        adminUserTF.setBorder(null);
        adminUserTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUserTFActionPerformed(evt);
            }
        });
        backgroundPanel.add(adminUserTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 190, -1));

        editProfileBT.setBackground(new java.awt.Color(65, 147, 211));
        editProfileBT.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        editProfileBT.setForeground(new java.awt.Color(255, 255, 255));
        editProfileBT.setText("Edit Profile");
        editProfileBT.setBorder(null);
        editProfileBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBTActionPerformed(evt);
            }
        });
        backgroundPanel.add(editProfileBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 720, 260, 90));

        addStudentBT.setBackground(new java.awt.Color(65, 147, 211));
        addStudentBT.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        addStudentBT.setForeground(new java.awt.Color(255, 255, 255));
        addStudentBT.setText("Add Student");
        addStudentBT.setBorder(null);
        addStudentBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBTActionPerformed(evt);
            }
        });
        backgroundPanel.add(addStudentBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 260, 90));

        createAccountBT.setBackground(new java.awt.Color(65, 147, 211));
        createAccountBT.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        createAccountBT.setForeground(new java.awt.Color(255, 255, 255));
        createAccountBT.setText("Create account");
        createAccountBT.setBorder(null);
        createAccountBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBTActionPerformed(evt);
            }
        });
        backgroundPanel.add(createAccountBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 260, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signOutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBTActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadScreen().setVisible(true);
            }
        });
    }//GEN-LAST:event_signOutBTActionPerformed

    private void editProfileBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBTActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        eprofile.setVisible(true);
        eprofile.account("admin",this);
        
    }//GEN-LAST:event_editProfileBTActionPerformed

    private void addStudentBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBTActionPerformed
        // TODO add your handling code here:
        createStudentScreen createStudent = new createStudentScreen();
        this.setVisible(false);
        createStudent.setVisible(true);
        createStudent.account(this);
        createStudent.getTeachers();
        
    }//GEN-LAST:event_addStudentBTActionPerformed

    private void createAccountBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBTActionPerformed
        // TODO add your handling code here:
        CreateAccountScreen createAccount = new CreateAccountScreen();
        this.setVisible(false);
        createAccount.setVisible(true);
        createAccount.account(this);
    }//GEN-LAST:event_createAccountBTActionPerformed

    private void adminTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminTxtActionPerformed

    private void adminUserTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUserTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminUserTFActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudentBT;
    private javax.swing.JLabel adminIcon;
    private javax.swing.JTextField adminTxt;
    private javax.swing.JTextField adminUserTF;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton createAccountBT;
    private javax.swing.JButton editProfileBT;
    private javax.swing.JButton signOutBT;
    // End of variables declaration//GEN-END:variables
    
     /**
     * Creates new form adminMainMenu
     */
    public adminMainMenu() {
        initComponents();
    }
    
    void Username(String uname) {
        username = uname;
        adminUserTF.setText(uname);
    }
}
