/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolproject;

/**
 *
 * @author seanb
 */
public class EditProfileScreen extends javax.swing.JFrame {
       private String type;
       
       private adminMainMenu adminMainMenu;
       private ParentMainMenu parentMainMenu;
       private TeacherMainMenu teacherMainMenu;
    /**
     * Creates new form adminEditProfile
     */
    public EditProfileScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        backBT = new javax.swing.JButton();
        editProfileIcon = new javax.swing.JLabel();
        editProfileTxt = new javax.swing.JTextField();
        newPwordTxt = new javax.swing.JTextField();
        newUsernameTF1 = new javax.swing.JTextField();
        editBT = new javax.swing.JButton();
        line = new javax.swing.JTextField();
        usernameTxt = new javax.swing.JTextField();
        newPF = new javax.swing.JPasswordField();
        oldPwordTxt = new javax.swing.JTextField();
        oldPF = new javax.swing.JPasswordField();
        editBT2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 1000));

        backgroundPanel.setBackground(new java.awt.Color(250, 228, 188));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(1000, 1000));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/backBT.png"))); // NOI18N
        backBT.setBorder(null);
        backBT.setOpaque(false);
        backBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTActionPerformed(evt);
            }
        });
        backgroundPanel.add(backBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 50, 50));

        editProfileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/editProfile.png"))); // NOI18N
        backgroundPanel.add(editProfileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 200, 200));

        editProfileTxt.setEditable(false);
        editProfileTxt.setBackground(new java.awt.Color(250, 228, 188));
        editProfileTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        editProfileTxt.setText("Edit Profile");
        editProfileTxt.setBorder(null);
        editProfileTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileTxtActionPerformed(evt);
            }
        });
        backgroundPanel.add(editProfileTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 160, -1));

        newPwordTxt.setEditable(false);
        newPwordTxt.setBackground(new java.awt.Color(250, 228, 188));
        newPwordTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        newPwordTxt.setText("New Username");
        newPwordTxt.setBorder(null);
        newPwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPwordTxtActionPerformed(evt);
            }
        });
        backgroundPanel.add(newPwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        newUsernameTF1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        backgroundPanel.add(newUsernameTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 250, 50));

        editBT.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        editBT.setText("Edit");
        editBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTActionPerformed(evt);
            }
        });
        backgroundPanel.add(editBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 160, 50));

        line.setEditable(false);
        line.setBackground(new java.awt.Color(65, 147, 211));
        line.setBorder(null);
        backgroundPanel.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 790, -1));

        usernameTxt.setEditable(false);
        usernameTxt.setBackground(new java.awt.Color(250, 228, 188));
        usernameTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        usernameTxt.setText("New Password");
        usernameTxt.setBorder(null);
        usernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtActionPerformed(evt);
            }
        });
        backgroundPanel.add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, -1, -1));
        backgroundPanel.add(newPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 670, 250, 50));

        oldPwordTxt.setEditable(false);
        oldPwordTxt.setBackground(new java.awt.Color(250, 228, 188));
        oldPwordTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        oldPwordTxt.setText("Old Password");
        oldPwordTxt.setBorder(null);
        oldPwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPwordTxtActionPerformed(evt);
            }
        });
        backgroundPanel.add(oldPwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 740, -1, -1));
        backgroundPanel.add(oldPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 780, 250, 50));

        editBT2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        editBT2.setText("Edit");
        editBT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBT2ActionPerformed(evt);
            }
        });
        backgroundPanel.add(editBT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 850, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        
        if(type.equals("admin")){
            adminMainMenu.setVisible(true);
        }else if(type.equals("teacher")){
            teacherMainMenu.setVisible(true);
        }else{
            parentMainMenu.setVisible(true);
        }
        
    }//GEN-LAST:event_backBTActionPerformed

    private void editProfileTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editProfileTxtActionPerformed

    private void editBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBTActionPerformed

    private void usernameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtActionPerformed

    private void newPwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPwordTxtActionPerformed

    private void oldPwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPwordTxtActionPerformed

    private void editBT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBT2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBT;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton editBT;
    private javax.swing.JButton editBT2;
    private javax.swing.JLabel editProfileIcon;
    private javax.swing.JTextField editProfileTxt;
    private javax.swing.JTextField line;
    private javax.swing.JPasswordField newPF;
    private javax.swing.JTextField newPwordTxt;
    private javax.swing.JTextField newUsernameTF1;
    private javax.swing.JPasswordField oldPF;
    private javax.swing.JTextField oldPwordTxt;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
    
    void account(String accountype,Object account){
        type =accountype;
        if(accountype.equals("admin")){
            adminMainMenu = (schoolproject.adminMainMenu) account;
        }else if(accountype.equals("teacher")){
            teacherMainMenu = (schoolproject.TeacherMainMenu) account;
        }else{
            parentMainMenu = (schoolproject.ParentMainMenu) account;
        }
    }
}
