/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolproject;

/**
 *
 * @author seanb
 */
public class TAssessmentScreen extends javax.swing.JFrame {

    /**
     * Creates new form TAssessmentScreen
     */
    public TAssessmentScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        backgroundPanel = new javax.swing.JPanel();
        backBT = new javax.swing.JButton();
        assessmentIcon = new javax.swing.JLabel();
        assessmentsTxt = new javax.swing.JTextField();
        studentTxt = new javax.swing.JTextField();
        studentCB = new javax.swing.JComboBox<>();
        noteTxt = new javax.swing.JTextField();
        noteCB = new javax.swing.JComboBox<>();
        descriptionTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTA = new javax.swing.JTextArea();
        dateTxt = new javax.swing.JTextField();
        dateTF = new javax.swing.JTextField();
        addBT = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 1000));

        backgroundPanel.setBackground(new java.awt.Color(250, 228, 188));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(1000, 1000));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/backBT.png"))); // NOI18N
        backBT.setBorder(null);
        backBT.setOpaque(false);
        backBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTActionPerformed(evt);
            }
        });
        backgroundPanel.add(backBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 50, 50));

        assessmentIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assessmentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/assessmentIcon.png"))); // NOI18N
        backgroundPanel.add(assessmentIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 200, 200));

        assessmentsTxt.setEditable(false);
        assessmentsTxt.setBackground(new java.awt.Color(250, 228, 188));
        assessmentsTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        assessmentsTxt.setText("Assessments");
        assessmentsTxt.setBorder(null);
        assessmentsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assessmentsTxtActionPerformed(evt);
            }
        });
        backgroundPanel.add(assessmentsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        studentTxt.setEditable(false);
        studentTxt.setBackground(new java.awt.Color(250, 228, 188));
        studentTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        studentTxt.setText("Student:");
        studentTxt.setBorder(null);
        studentTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentTxtActionPerformed(evt);
            }
        });
        backgroundPanel.add(studentTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        studentCB.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        backgroundPanel.add(studentCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 250, 50));

        noteTxt.setEditable(false);
        noteTxt.setBackground(new java.awt.Color(250, 228, 188));
        noteTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        noteTxt.setText("Note:");
        noteTxt.setBorder(null);
        noteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteTxtActionPerformed(evt);
            }
        });
        backgroundPanel.add(noteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        noteCB.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        noteCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excellent Work", "Workin Hard", "No Homework", "Distracted", "Disruptive", "Talkative", "Absent" }));
        backgroundPanel.add(noteCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 250, 50));

        descriptionTxt.setEditable(false);
        descriptionTxt.setBackground(new java.awt.Color(250, 228, 188));
        descriptionTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        descriptionTxt.setText("Description:");
        descriptionTxt.setBorder(null);
        descriptionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTxtActionPerformed(evt);
            }
        });
        backgroundPanel.add(descriptionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, -1, -1));

        descriptionTA.setColumns(20);
        descriptionTA.setRows(5);
        jScrollPane1.setViewportView(descriptionTA);

        backgroundPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 240, 150));

        dateTxt.setEditable(false);
        dateTxt.setBackground(new java.awt.Color(250, 228, 188));
        dateTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        dateTxt.setText("Date:");
        dateTxt.setBorder(null);
        dateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTxtActionPerformed(evt);
            }
        });
        backgroundPanel.add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, -1, -1));

        dateTF.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        backgroundPanel.add(dateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 250, 50));

        addBT.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        addBT.setText("Add Assessment");
        addBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTActionPerformed(evt);
            }
        });
        backgroundPanel.add(addBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 780, 230, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assessmentsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assessmentsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assessmentsTxtActionPerformed

    private void studentTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentTxtActionPerformed

    private void noteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noteTxtActionPerformed

    private void descriptionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionTxtActionPerformed

    private void dateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTxtActionPerformed

    private void addBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBTActionPerformed

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBTActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBT;
    private javax.swing.JLabel assessmentIcon;
    private javax.swing.JTextField assessmentsTxt;
    private javax.swing.JButton backBT;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JTextField dateTF;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JTextArea descriptionTA;
    private javax.swing.JTextField descriptionTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> noteCB;
    private javax.swing.JTextField noteTxt;
    private javax.swing.JComboBox<String> studentCB;
    private javax.swing.JTextField studentTxt;
    // End of variables declaration//GEN-END:variables
}
