/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolproject;

/**
 *
 * @author seanb
 */
public class CreateAccountScreen extends javax.swing.JFrame {
    private adminMainMenu adminMainMenu;
    /**
     * Creates new form CreateAccountScreen
     */
    public CreateAccountScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        createStudentIcon = new javax.swing.JLabel();
        backBT = new javax.swing.JButton();
        forenameTxt1 = new javax.swing.JTextField();
        foreNameTF = new javax.swing.JTextField();
        sureNameTxt = new javax.swing.JTextField();
        surenameTF = new javax.swing.JTextField();
        enrolledTxt = new javax.swing.JTextField();
        enrolledTF = new javax.swing.JTextField();
        addParentBT = new javax.swing.JButton();
        line = new javax.swing.JTextField();
        createAccoutTxt = new javax.swing.JTextField();
        tforenameTxt = new javax.swing.JTextField();
        tforenmaeTF = new javax.swing.JTextField();
        tsurenameTxt = new javax.swing.JTextField();
        tsurenameTF = new javax.swing.JTextField();
        subjectTxt = new javax.swing.JTextField();
        addTeacherBT = new javax.swing.JButton();
        subjectCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 1000));

        backgroundPanel.setBackground(new java.awt.Color(250, 228, 188));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(1000, 1000));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createStudentIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createStudentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/createAccount.png"))); // NOI18N
        backgroundPanel.add(createStudentIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 200, 200));

        backBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/backBT.png"))); // NOI18N
        backBT.setBorder(null);
        backBT.setOpaque(false);
        backBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTActionPerformed(evt);
            }
        });
        backgroundPanel.add(backBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 50, 50));

        forenameTxt1.setEditable(false);
        forenameTxt1.setBackground(new java.awt.Color(250, 228, 188));
        forenameTxt1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        forenameTxt1.setText("Parent Forename:");
        forenameTxt1.setBorder(null);
        backgroundPanel.add(forenameTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        foreNameTF.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        backgroundPanel.add(foreNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 250, 50));

        sureNameTxt.setEditable(false);
        sureNameTxt.setBackground(new java.awt.Color(250, 228, 188));
        sureNameTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        sureNameTxt.setText("Parent Surname:");
        sureNameTxt.setBorder(null);
        backgroundPanel.add(sureNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        surenameTF.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        backgroundPanel.add(surenameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 250, 50));

        enrolledTxt.setEditable(false);
        enrolledTxt.setBackground(new java.awt.Color(250, 228, 188));
        enrolledTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        enrolledTxt.setText("Enrolled Child:");
        enrolledTxt.setBorder(null);
        backgroundPanel.add(enrolledTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 670, -1, -1));

        enrolledTF.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        enrolledTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrolledTFActionPerformed(evt);
            }
        });
        backgroundPanel.add(enrolledTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 710, 250, 50));

        addParentBT.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        addParentBT.setText("Add Parent");
        addParentBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addParentBTActionPerformed(evt);
            }
        });
        backgroundPanel.add(addParentBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 800, 160, 50));

        line.setEditable(false);
        line.setBackground(new java.awt.Color(65, 147, 211));
        line.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineActionPerformed(evt);
            }
        });
        backgroundPanel.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 10, 490));

        createAccoutTxt.setEditable(false);
        createAccoutTxt.setBackground(new java.awt.Color(250, 228, 188));
        createAccoutTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        createAccoutTxt.setText("Create Account");
        createAccoutTxt.setBorder(null);
        createAccoutTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccoutTxtActionPerformed(evt);
            }
        });
        backgroundPanel.add(createAccoutTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 220, -1));

        tforenameTxt.setEditable(false);
        tforenameTxt.setBackground(new java.awt.Color(250, 228, 188));
        tforenameTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        tforenameTxt.setText("Teacher Forename:");
        tforenameTxt.setBorder(null);
        backgroundPanel.add(tforenameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, -1, -1));

        tforenmaeTF.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        backgroundPanel.add(tforenmaeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 250, 50));

        tsurenameTxt.setEditable(false);
        tsurenameTxt.setBackground(new java.awt.Color(250, 228, 188));
        tsurenameTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        tsurenameTxt.setText("Teacher Surname:");
        tsurenameTxt.setBorder(null);
        tsurenameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsurenameTxtActionPerformed(evt);
            }
        });
        backgroundPanel.add(tsurenameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, -1, -1));

        tsurenameTF.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        backgroundPanel.add(tsurenameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 250, 50));

        subjectTxt.setEditable(false);
        subjectTxt.setBackground(new java.awt.Color(250, 228, 188));
        subjectTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        subjectTxt.setText("Subject:");
        subjectTxt.setBorder(null);
        backgroundPanel.add(subjectTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 670, -1, -1));

        addTeacherBT.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        addTeacherBT.setText("Add Teacher");
        addTeacherBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherBTActionPerformed(evt);
            }
        });
        backgroundPanel.add(addTeacherBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 800, 160, 50));

        subjectCB.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        subjectCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maths", "English", "Irish", "Chemistry", "Business", "French" }));
        backgroundPanel.add(subjectCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 710, 250, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         adminMainMenu.setVisible(true);
    }//GEN-LAST:event_backBTActionPerformed

    private void enrolledTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrolledTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrolledTFActionPerformed

    private void addParentBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addParentBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addParentBTActionPerformed

    private void lineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineActionPerformed

    private void addTeacherBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTeacherBTActionPerformed

    private void tsurenameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsurenameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsurenameTxtActionPerformed

    private void createAccoutTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccoutTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createAccoutTxtActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addParentBT;
    private javax.swing.JButton addTeacherBT;
    private javax.swing.JButton backBT;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JTextField createAccoutTxt;
    private javax.swing.JLabel createStudentIcon;
    private javax.swing.JTextField enrolledTF;
    private javax.swing.JTextField enrolledTxt;
    private javax.swing.JTextField foreNameTF;
    private javax.swing.JTextField forenameTxt1;
    private javax.swing.JTextField line;
    private javax.swing.JComboBox<String> subjectCB;
    private javax.swing.JTextField subjectTxt;
    private javax.swing.JTextField sureNameTxt;
    private javax.swing.JTextField surenameTF;
    private javax.swing.JTextField tforenameTxt;
    private javax.swing.JTextField tforenmaeTF;
    private javax.swing.JTextField tsurenameTF;
    private javax.swing.JTextField tsurenameTxt;
    // End of variables declaration//GEN-END:variables

    void account(Object account) {

        adminMainMenu = (schoolproject.adminMainMenu) account;
    }      
}
