/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolproject;

/**
 *
 * @author seanb
 */
 final class LoadScreen extends javax.swing.JFrame {
     
     private String button;
     SignInScreen signIn;
    /**
     * Creates new form LoadScreen
     */
    public LoadScreen() {
        initComponents();
        signIn = new SignInScreen();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        logoTF = new javax.swing.JTextField();
        aminBT = new javax.swing.JButton();
        teacherBT = new javax.swing.JButton();
        parentBT = new javax.swing.JButton();
        exitBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setSize(new java.awt.Dimension(1000, 1000));

        backgroundPanel.setBackground(new java.awt.Color(250, 228, 188));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/SchoolPortalIcon.png"))); // NOI18N
        backgroundPanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 200, 200));

        logoTF.setEditable(false);
        logoTF.setBackground(new java.awt.Color(250, 228, 188));
        logoTF.setFont(new java.awt.Font("Tw Cen MT", 0, 50)); // NOI18N
        logoTF.setForeground(new java.awt.Color(65, 147, 211));
        logoTF.setText("School Portal");
        logoTF.setBorder(null);
        logoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoTFActionPerformed(evt);
            }
        });
        backgroundPanel.add(logoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 260, -1));

        aminBT.setBackground(new java.awt.Color(65, 147, 211));
        aminBT.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        aminBT.setForeground(new java.awt.Color(255, 255, 255));
        aminBT.setText("Admin User");
        aminBT.setBorder(null);
        aminBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aminBTActionPerformed(evt);
            }
        });
        backgroundPanel.add(aminBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 260, 90));

        teacherBT.setBackground(new java.awt.Color(65, 147, 211));
        teacherBT.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        teacherBT.setForeground(new java.awt.Color(255, 255, 255));
        teacherBT.setText("Teacher User");
        teacherBT.setBorder(null);
        teacherBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherBTActionPerformed(evt);
            }
        });
        backgroundPanel.add(teacherBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, 260, 90));

        parentBT.setBackground(new java.awt.Color(65, 147, 211));
        parentBT.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        parentBT.setForeground(new java.awt.Color(255, 255, 255));
        parentBT.setText("Parent User");
        parentBT.setBorder(null);
        parentBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentBTActionPerformed(evt);
            }
        });
        backgroundPanel.add(parentBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 720, 260, 90));

        exitBT.setBackground(new java.awt.Color(250, 228, 188));
        exitBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/exit.png"))); // NOI18N
        exitBT.setBorder(null);
        exitBT.setOpaque(false);
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });
        backgroundPanel.add(exitBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 880, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoTFActionPerformed

    private void parentBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentBTActionPerformed
        this.setVisible(false);
       button = "parent";
       signIn.setVisible(true);
       signIn.Type(button);
    }//GEN-LAST:event_parentBTActionPerformed

    private void aminBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aminBTActionPerformed
       this.setVisible(false);
       button = "admin";
       signIn.setVisible(true);
       signIn.Type(button);
    }//GEN-LAST:event_aminBTActionPerformed

    private void teacherBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherBTActionPerformed
        this.setVisible(false);
       button = "teacher";
       signIn.setVisible(true);
       signIn.Type(button);
    }//GEN-LAST:event_teacherBTActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBTActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aminBT;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton exitBT;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTextField logoTF;
    private javax.swing.JButton parentBT;
    private javax.swing.JButton teacherBT;
    // End of variables declaration//GEN-END:variables
}
