/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolproject;

/**
 *
 * @author seanb
 */
public class TeacherMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form TeacherMainMenu
     */
    public TeacherMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel1 = new javax.swing.JPanel();
        teacherIcon = new javax.swing.JLabel();
        teacherTxt = new javax.swing.JTextField();
        teacherTF = new javax.swing.JTextField();
        subjectTxt = new javax.swing.JTextField();
        subjectTF = new javax.swing.JTextField();
        assessmentBT = new javax.swing.JButton();
        reportsBT = new javax.swing.JButton();
        editProfileBT = new javax.swing.JButton();
        signOutBT1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 1000));

        backgroundPanel1.setBackground(new java.awt.Color(250, 228, 188));
        backgroundPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));
        backgroundPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teacherIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teacherIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/techerIcon.png"))); // NOI18N
        backgroundPanel1.add(teacherIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 200, 200));

        teacherTxt.setEditable(false);
        teacherTxt.setBackground(new java.awt.Color(250, 228, 188));
        teacherTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        teacherTxt.setText("Teacher User:");
        teacherTxt.setBorder(null);
        teacherTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherTxtActionPerformed(evt);
            }
        });
        backgroundPanel1.add(teacherTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        teacherTF.setEditable(false);
        teacherTF.setBackground(new java.awt.Color(250, 228, 188));
        teacherTF.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        teacherTF.setText("Jerry12");
        teacherTF.setBorder(null);
        teacherTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherTFActionPerformed(evt);
            }
        });
        backgroundPanel1.add(teacherTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 190, -1));

        subjectTxt.setEditable(false);
        subjectTxt.setBackground(new java.awt.Color(250, 228, 188));
        subjectTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        subjectTxt.setText("Subject:");
        subjectTxt.setBorder(null);
        subjectTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectTxtActionPerformed(evt);
            }
        });
        backgroundPanel1.add(subjectTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        subjectTF.setEditable(false);
        subjectTF.setBackground(new java.awt.Color(250, 228, 188));
        subjectTF.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        subjectTF.setText("Maths");
        subjectTF.setBorder(null);
        subjectTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectTFActionPerformed(evt);
            }
        });
        backgroundPanel1.add(subjectTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 120, -1));

        assessmentBT.setBackground(new java.awt.Color(65, 147, 211));
        assessmentBT.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        assessmentBT.setText("Assessments");
        assessmentBT.setBorder(null);
        assessmentBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assessmentBTActionPerformed(evt);
            }
        });
        backgroundPanel1.add(assessmentBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 260, 90));

        reportsBT.setBackground(new java.awt.Color(65, 147, 211));
        reportsBT.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        reportsBT.setText("Weekly Reports");
        reportsBT.setBorder(null);
        reportsBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsBTActionPerformed(evt);
            }
        });
        backgroundPanel1.add(reportsBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, 260, 90));

        editProfileBT.setBackground(new java.awt.Color(65, 147, 211));
        editProfileBT.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        editProfileBT.setText("Edit Profile");
        editProfileBT.setBorder(null);
        editProfileBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBTActionPerformed(evt);
            }
        });
        backgroundPanel1.add(editProfileBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 720, 260, 90));

        signOutBT1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        signOutBT1.setText("Sign Out");
        signOutBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBT1ActionPerformed(evt);
            }
        });
        backgroundPanel1.add(signOutBT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editProfileBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editProfileBTActionPerformed

    private void assessmentBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assessmentBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assessmentBTActionPerformed

    private void reportsBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportsBTActionPerformed

    private void teacherTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherTxtActionPerformed

    private void teacherTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherTFActionPerformed

    private void signOutBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signOutBT1ActionPerformed

    private void subjectTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectTxtActionPerformed

    private void subjectTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectTFActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assessmentBT;
    private javax.swing.JPanel backgroundPanel1;
    private javax.swing.JButton editProfileBT;
    private javax.swing.JButton reportsBT;
    private javax.swing.JButton signOutBT1;
    private javax.swing.JTextField subjectTF;
    private javax.swing.JTextField subjectTxt;
    private javax.swing.JLabel teacherIcon;
    private javax.swing.JTextField teacherTF;
    private javax.swing.JTextField teacherTxt;
    // End of variables declaration//GEN-END:variables
}
